config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome', as: :welcome
  get 'projects', to: 'pages#projects', as: :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Rubén Giráldez - Portfolio</title>
    <!-- Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/pages.css.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  </head>
  <body>
  <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Rubén Giráldez</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="<%= welcome_path %>"> Home</a>
                </li>
            </ul>
        </div>
    </nav>
    <%= yield %>
    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col">
                    <!-- Social Media Icons and Links -->
                    <a href="https://github.com/rrg97" target="_blank"><i class="fab fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/rub%C3%A9n-gir%C3%A1ldez-de-la-fuente-184285216/" target="_blank"><i class="fab fa-linkedin"></i></a>
                    <a href="https://twitter.com/tesla" target="_blank"><i class="fab fa-twitter"></i></a>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <p class="copyright">&copy; 2024 Rubén Giráldez. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/projects.html.erb
<link rel="stylesheet" href="css/projects.css.scss">
<link rel="stylesheet" href="css/pages.css.scss">
<section class="fav-project-section">
     <div class="container d-flex flex-column align-items-center justify-content-end min-vh-100">
    </div>
</section>

<div class="row">
  <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
    <img
      src="https://i.imgur.com/BOWKu5s.png"
      class="w-100 shadow-1-strong rounded mb-4"
    />

    <img
      src="https://i.imgur.com/xTqkXGk.png"
      class="w-100 shadow-1-strong rounded mb-4"
    />
  </div>

  <div class="col-lg-4 mb-4 mb-lg-0">
    <img
      src="https://i.imgur.com/fy8g3j9.png"
      class="w-100 shadow-1-strong rounded mb-4"
    />

    <img
      src="https://imgur.com/2WcPUj8.png"
      class="w-100 shadow-1-strong rounded mb-4"
    />
  </div>

  <div class="col-lg-4 mb-4 mb-lg-0">
    <img
      src="https://imgur.com/C9WtWcM.png"
      class="w-100 shadow-1-strong rounded mb-4"
    />

    <img
      src="https://imgur.com/C4IFHuh.png"
      class="w-100 shadow-1-strong rounded mb-4"
    />
  </div>
</div>

app/views/pages/welcome.html.erb
<section class="main-section">
    <div class="container d-flex flex-column align-items-center justify-content-end min-vh-100">
        <img src="https://i.imgur.com/t9DAwuu.png" alt="Your Photo" class="img-fluid rounded-circle" style="max-height: 400px;margin-top: 50px">
        <h1>Rubén Giráldez</h1>
        <p class="tagline">Always learning 🔬</p>
        <a href="<%= projects_path %>" id="view-my-work" class="btn btn-primary mt-auto">View my Work</a>
    </div>
  </section>